# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 1000
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: ${env:DATA_ROOT}/eat-em2v/baselines
  seed: 42

checkpoint:
  save_interval: 5
  no_epoch_checkpoints: false

task:
  _name: mae_image_pretraining
  data: ${env:DATA_ROOT}/manifests/pretrain
  rebuild_batches: true
  key: source
  precompute_mask_config: {}
  downsr_16hz: true
  audio_mae: true
  h5_format: false
  target_length: 1024
  flexible_mask: false
  wandb_project: emotion2vec-eat
  wandb_run_name: eat-ser-pretrain
  wandb_group: eat-ser-pretrain-seed42
  wandb_job_type: pretrain
  wandb_enable: true

dataset:
  num_workers: 10
  batch_size: 64
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  disable_validation: true
  valid_subset: train

distributed_training:
  distributed_world_size: 1
  ddp_backend: c10d

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - masked_pct

optimization:
  max_update: 230000
  lr: [ 5e-5 ]
  max_epoch: 5
  clip_norm: 4

optimizer:
  _name: composite
  groups:
    default:
      lr_float: 5e-5
      optimizer:
        _name: adam
        adam_betas: [0.9, 0.95]
        weight_decay: 1e-2
      lr_scheduler:
        _name: cosine
        warmup_updates: 30000  # scale to dataset size
        min_lr: 1e-6

lr_scheduler: pass_through

model:
  _name: data2vec_multi

  ema_decay: 0.9998
  ema_end_decay: 0.99999
  ema_anneal_end_step: 100000
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: true
  end_of_block_targets: false

  depth: 12
  average_top_k_layers: 12
  clone_batch: 8

  norm_eps: 1e-6
  layer_decay: 0.65
  no_decay_blocks: true

  min_target_var: 0
  min_pred_var: 0

  encoder_dropout: 0
  post_mlp_drop: 0
  attention_dropout: 0
  activation_dropout: 0

  supported_modality: IMAGE
  cls_loss: 1

  ema_encoder_only: false

  modalities:
    image:
      in_chans: 1
      inverse_mask: true
      mask_prob: 0.8
      mask_prob_adjust: 0.07
      mask_length: 5
      mask_noise_std: 0.01
      prenet_depth: 0
      ema_local_encoder: true
      num_extra_tokens: 1
      init_extra_token_zero: false
      use_alibi_encoder: false
      decoder:
        decoder_dim: 768
        decoder_groups: 16
        decoder_kernel: 3
        decoder_layers: 6
        input_dropout: 0
